version: '3.4'
services:
  db:
    image: murilofelpeto/aluguel-mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build: 
      context: .
      dockerfile: containers/DB/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_USER: murilofelpeto
      MYSQL_ROOT_PASSWORD: Murilo!8
      MYSQL_PASSWORD: Murilo18
      MYSQL_DATABASE: aluguel
    ports:
      - "3306:3306"
    networks:
      - aluguel-network
  aluguel-api:
    image: murilofelpeto/aluguel-api
    restart: always
    build: 
      context: ./aluguel
      dockerfile: ../containers/App/Dockerfile
    working_dir: /aluguel
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./aluguel:/aluguel
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - aluguel-network
networks:
    aluguel-network:
        driver: bridge