insert into endereco (bairro, cep, cidade, complemento, estado, logradouro, numero) values ('Aplicare Povidone Iodine Swabstick', 10285263, 'Baton Rouge', 'Penthouse', 'LA', 'Lindbergh', '53893');
insert into endereco (bairro, cep, cidade, complemento, estado, logradouro, numero) values ('PROPRANOLOL HYDROCHLORIDE', 16298823, 'Milwaukee', 'Hamburger Hill', 'WI', 'Arizona', '10194');
insert into endereco (bairro, cep, cidade, complemento, estado, logradouro, numero) values ('everyone Hand Sanitizer', 88236803, 'Bakersfield', 'The Losers', 'CA', 'Morning', '35200');
insert into endereco (bairro, cep, cidade, complemento, estado, logradouro, numero) values ('DOUBLE PERFECTION LUMIERE', 95689415, 'Kansas City', 'Adventures of Baron Munchausen, The', 'MO', 'Center', '8231');
insert into endereco (bairro, cep, cidade, complemento, estado, logradouro, numero) values ('Triamterene and Hydrochlorothiazide', 24798382, 'Dallas', 'Heartbreaker (L''Arnacoeur)', 'TX', 'Forest', '3909');
insert into endereco (bairro, cep, cidade, complemento, estado, logradouro, numero) values ('Pleo Ut S', 63513132, 'Palm Bay', 'No Good Deed', 'FL', 'Boyd', '52');
insert into endereco (bairro, cep, cidade, complemento, estado, logradouro, numero) values ('Fentanyl Citrate', 46896902, 'El Paso', 'Ladrón que roba a ladrón', 'TX', 'La Follette', '98249');
insert into endereco (bairro, cep, cidade, complemento, estado, logradouro, numero) values ('Percy Medicine', 13513977, 'Portland', 'Slaughter of the Innocents', 'OR', 'Summit', '5215');
insert into endereco (bairro, cep, cidade, complemento, estado, logradouro, numero) values ('Slim 2', 32063621, 'Kalamazoo', 'Happy Poet, The', 'MI', 'International', '871');
insert into endereco (bairro, cep, cidade, complemento, estado, logradouro, numero) values ('Balsalazide Disodium', 22544482, 'Lake Charles', 'This Is Where I Leave You', 'LA', 'Lake View', '78');
insert into endereco (bairro, cep, cidade, complemento, estado, logradouro, numero) values ('TOPCARE MAXIMUM STRENGTH URINARY PAIN RELIEF', 12876285, 'New York City', 'Where the Wild Things Are', 'NY', 'Banding', '0');
insert into endereco (bairro, cep, cidade, complemento, estado, logradouro, numero) values ('Gliadel', 65081990, 'Washington', 'Wall, The (Die Wand)', 'DC', 'Westerfield', '52615');
insert into endereco (bairro, cep, cidade, complemento, estado, logradouro, numero) values ('Procainamide Hydrochloride', 41856747, 'Philadelphia', 'Night of the Running Man', 'PA', 'Dawn', '3701');
insert into endereco (bairro, cep, cidade, complemento, estado, logradouro, numero) values ('Body Blends Vanilla Sugar Anti-bacterial Hand Sanitizer', 34906787, 'Detroit', 'Shout', 'MI', 'Pawling', '0');
insert into endereco (bairro, cep, cidade, complemento, estado, logradouro, numero) values ('Fexofenadine Hydrochloride', 55209743, 'Midland', 'Meet Me in St. Louis', 'TX', 'Service', '73107');
insert into endereco (bairro, cep, cidade, complemento, estado, logradouro, numero) values ('REQUIP', 63174613, 'Cleveland', 'One Hundred Mornings', 'OH', 'Charing Cross', '4');
insert into endereco (bairro, cep, cidade, complemento, estado, logradouro, numero) values ('ACETAMINOPHEN AND CODEINE PHOSPHATE', 15818921, 'Cincinnati', 'Cobra Woman', 'OH', 'Waubesa', '771');
insert into endereco (bairro, cep, cidade, complemento, estado, logradouro, numero) values ('AMMONIA N-13', 88095456, 'New Bedford', 'You Got Served', 'MA', 'Schlimgen', '571');
insert into endereco (bairro, cep, cidade, complemento, estado, logradouro, numero) values ('FENTANYL', 41596816, 'White Plains', 'Nightcrawler', 'NY', 'Algoma', '290');
insert into endereco (bairro, cep, cidade, complemento, estado, logradouro, numero) values ('Chlorogenic Acid', 80071343, 'Escondido', 'Lucky: No Time For Love', 'CA', 'Fordem', '900');
